table sample_sales_dataset
	lineageTag: 4f9d372f-2012-4e39-98cc-569edc260a6b

	column Order_ID
		dataType: int64
		formatString: 0
		lineageTag: e3016fc1-930e-4fd0-b0e1-08f47c1330d2
		summarizeBy: count
		sourceColumn: Order_ID

		annotation SummarizationSetBy = Automatic

	column Date
		dataType: dateTime
		formatString: Long Date
		lineageTag: 35575f4c-dc38-4bcc-827d-b99088bcb9c8
		summarizeBy: none
		sourceColumn: Date

		variation Variation
			isDefault
			relationship: 7cff1e5e-59ff-4be7-b640-9b2c8537250e
			defaultHierarchy: LocalDateTable_5ed337ca-22b8-46c0-922b-79f11cbbc9ab.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Customer
		dataType: string
		lineageTag: eff7bf20-a287-45cb-acc1-0d0a98df1217
		summarizeBy: none
		sourceColumn: Customer

		annotation SummarizationSetBy = Automatic

	column Product
		dataType: string
		lineageTag: 225e19ff-52af-4ec2-a955-3aa75b19dfcb
		summarizeBy: none
		sourceColumn: Product

		annotation SummarizationSetBy = Automatic

	column Category
		dataType: string
		lineageTag: 79b0fe3a-cc3b-4685-b516-06e4d525875f
		summarizeBy: none
		sourceColumn: Category

		annotation SummarizationSetBy = Automatic

	column Quantity
		dataType: int64
		formatString: 0
		lineageTag: 0930c75b-e71c-4323-959a-01e51ea0afce
		summarizeBy: sum
		sourceColumn: Quantity

		annotation SummarizationSetBy = Automatic

	column Unit_Price
		dataType: int64
		formatString: 0
		lineageTag: a21af20f-3a12-4753-b0f5-3ba78ba90708
		summarizeBy: sum
		sourceColumn: Unit_Price

		annotation SummarizationSetBy = Automatic

	column Total_Amount
		dataType: int64
		formatString: 0
		lineageTag: 062e6afd-b604-4af2-9c1c-9a44afc056c9
		summarizeBy: sum
		sourceColumn: Total_Amount

		annotation SummarizationSetBy = Automatic

	partition sample_sales_dataset = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\prade\Downloads\sample_sales_dataset.csv"),[Delimiter=",", Columns=8, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Order_ID", Int64.Type}, {"Date", type date}, {"Customer", type text}, {"Product", type text}, {"Category", type text}, {"Quantity", Int64.Type}, {"Unit_Price", Int64.Type}, {"Total_Amount", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

