table order_details
	lineageTag: a702ad97-cf69-4057-9af4-197bd14a9e68

	measure 'Shipment Revenue' =
			
			CALCULATE(
			SUMX(
			    order_details,
			    order_details[Quantity] * order_details[Revenue]
			),
			    USERELATIONSHIP(order_details[Shipment_Date], date_dim[Date])
			)
		formatString: 0
		lineageTag: 66901d3a-3f9b-4a73-b35f-cf4660f2e5e6

	measure 'Total Amount' =
			
			SUMX(
			    order_details,
			    order_details[Quantity] * order_details[Revenue]
			)
		formatString: 0
		lineageTag: 4e9a5fc8-631b-4c92-9cce-01d245e896bb

	column Order_ID
		dataType: int64
		formatString: 0
		lineageTag: 6a941de8-5f93-4366-8aa4-f71dd4ea3271
		summarizeBy: count
		sourceColumn: Order_ID

		annotation SummarizationSetBy = Automatic

	column Customer_Name
		dataType: string
		lineageTag: 297c117e-d3b9-4556-a421-e868ae753a80
		summarizeBy: none
		sourceColumn: Customer_Name

		annotation SummarizationSetBy = Automatic

	column Product
		dataType: string
		lineageTag: 891e2d60-a784-4d5f-a139-b9630dcf59ea
		summarizeBy: none
		sourceColumn: Product

		annotation SummarizationSetBy = Automatic

	column Order_Date
		dataType: dateTime
		formatString: Long Date
		lineageTag: e56d852b-c818-40b7-a0b9-759529f9714a
		summarizeBy: none
		sourceColumn: Order_Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Shipment_Date
		dataType: dateTime
		formatString: Long Date
		lineageTag: 4681f0f0-0ebd-46ee-af52-9307459672ef
		summarizeBy: none
		sourceColumn: Shipment_Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Quantity
		dataType: int64
		formatString: 0
		lineageTag: 9ce2a3bb-0d8e-46a2-be9a-3a46de85a364
		summarizeBy: sum
		sourceColumn: Quantity

		annotation SummarizationSetBy = Automatic

	column Revenue
		dataType: int64
		formatString: 0
		lineageTag: 3840a33a-1f5a-4a40-a74e-482bec6fd232
		summarizeBy: sum
		sourceColumn: Revenue

		annotation SummarizationSetBy = Automatic

	partition order_details = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\Users\prade\Downloads\pract_order.xlsx"), null, true),
				    Sheet1_Sheet = Source{[Item="Sheet1",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(Sheet1_Sheet, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Order_ID", Int64.Type}, {"Customer_Name", type text}, {"Product", type text}, {"Order_Date", type date}, {"Shipment_Date", type date}, {"Quantity", Int64.Type}, {"Revenue", Int64.Type}})
				in
				    #"Changed Type"

	changedProperty = Name

	annotation PBI_ResultType = Table

